// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections.Generic;

public class ItemsCostCSV : MonoBehaviour
{
    public TextAsset mytxtData;

    public List<ItemValue> itemsValue = new List<ItemValue>();

    private void Start()
    {
        LoadCSV();
    }
    public void LoadCSV()  //add
    {

        string txt = mytxtData.text;
        string[] lines = txt.Split("\n");
        foreach (var item in lines)
        {
            string[] parts = item.Split(",");

            ItemValue iv = new ItemValue();

            iv.Name = parts[0];
            iv.Level = int.Parse(parts[1]);
            iv.Coins = int.Parse(parts[2]);
            iv.Mana = int.Parse(parts[3]);
            iv.Wood = int.Parse(parts[4]);
            iv.Stone = int.Parse(parts[5]);
            itemsValue.Add(iv);
        }
    }
}
